# Open Graph protocol
open_graph: true

# User info
user:
  name: Wenjie Hu
  first_name: Blog
  last_name: Clark's
  email: wenjie.hoo@outlook.com
  domain: ç«™ç‚¹åŸŸå
  avatar: /img/H.png
  describe: You are such fantastic human being.
  rule_text: ciao!

# Configure the icon information of the site
favicon:
  logo: /img/favicon.png
  icon16: /img/favicon.ico
  icon32: /img/favicon.ico
  apple_touch_icon: 
  webmanifest:
  visibilitychange: true
  # hidden: /failure.ico # Displays an icon when not visible
  hidden: /img/favicon.png
  show_text: favicon.show_text
  hide_text: favicon.hide_text


# Theme resource files or plug-ins
assets:
  # The cdn configuration of the js inside the theme
  internal_provider: local
  # cdn configuration of third-party js
  third_party_provider: unpkg
  # The plug-in used by the theme
  plugin:
    hexo_theme_async:
      rowcss: css/plugins/bootstrap.row.css
      typing: js/plugins/typing.js
      search: js/plugins/local_search.js
			danmu: js/plugins/danmu.js
      main: js/main.js
  # Icon configuration
  icons: 
    type: font # font symbol
    css:  css/plugins/font-awesome.min.css
    js:

# CDN User - defined plug-in
cdn:
  css: 
  js:
    head:
    base: 
    async: 
    defer: 

# The icon used by the theme
icons:
  # Theme switch icon
  sun: far fa-sun
  moon: far fa-moon
  # Home video play
  play: fas fa-play
  # email icon
  email: far fa-envelope
  # Category entry icon
  next: fas fa-arrow-right
  # Date of article details
  calendar: far fa-calendar-alt
  # Article details time
  clock: far fa-clock
  # Author of article details
  user: far fa-user
  # Return to the top icon
  back_top: fas fa-arrow-up
  # close icon
  close: fas fa-times
  # search icon
  search: fas fa-search
  # reward icon
  reward: fas fa-hand-holding-usd
  # User information and article directory switch
  user_tag: fas fa-user-alt
  toc_tag: fas fa-th-list
  # Secure the button in the lower right corner
  read: fas fa-book-reader
  arrows: fas fa-arrows-alt-h
  # Code highlight fold icon
  double_arrows: fas fa-angle-double-down
  # Code copy icon
  copy: fas fa-copy

# Top navigation menu
top_bars:
  - title: menu.home
    url: /
  - title: Archives
    url: '#'
    noswup: true
    children:
      - title: year
        url: /archives/
      - title: Tech
        url: /categories/tech/
      - title: travel
        url: /categories/travel/
      - title: thought
        url: /categories/thought/
      - title: math
        url: /categories/math/
  - title: Gallery
    url: /gallery/
  - title: menu.about
    url: /about/


# Banner settings
banner:
  use_cover: true
	danmu: 
		enable: false
		el: .trm-banner
  default:
    type: video #imgã€slideshowã€video
    # bgurl: /img/banner.png
    # bgurl: https://videos.pexels.com/video-files/1851190/1851190-uhd_2560_1440_25fps.mp4
    bgurl: https://videos.pexels.com/video-files/857251/857251-hd_1620_1080_25fps.mp4
    banner_text: How're ya goin' mate ?
    position: top
    fit: cover
  index:
    banner_title: Ciao!
    banner_text: How're ya goin' mate ?
    video_url: 
  archive:
    banner_title: Comment Ã§a va ?
    banner_text: The article archive
  links:
    banner_title: è«æ„å‰è·¯æ— çŸ¥å·±ï¼Œ<br>å¤©ä¸‹è°äººä¸è¯†å›ã€‚
    banner_text: A link to a friend's website
  comment:
    banner_title: ä½ å¥½ï¼Œ<br> ä»Šå¤©çš„å¤©æ°£æ€éº¼æ¨£ã€‚
    banner_text: The magic tree hole
  about:
    banner_title: ä½ è¯´å¾—å¯¹ï¼Œ<br>ç« é±¼å“¥ã€‚
    banner_text: About me

# Sidebar settings
sidebar:
  typed_text_prefix: ä½ å¥½ï¼Œ
  typed_text: ["ä»Šå¤©çš„å¤©æ°£æ€éº¼æ¨£ï¼Ÿ"]

  info: 
    - key: sidebar.city
      val: WrocÅ‚aw ğŸ‡µğŸ‡±
    - key: Job
      val: FBI
      
  social:
    - name: Github
      icon: fab fa-github
      url: https://github.com/wenjie-hoo
    - name: Linkedin
      icon: fab fa-linkedin
      url: https://www.linkedin.com/in/wenjie-hu/
    - name: Instagram
      icon: fab fa-instagram
      url: https://www.instagram.com/clark_hoo/
    - name: wechat
      icon: fab fa-weixin
      url: https://s2.loli.net/2023/09/22/Ll743X5Pxp68sFd.jpg
# About page settings
about:
	insert: before # before | after | none
  title: <iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/5H7ixXZfsNMGbIE5OBSpcb?utm_source=generator" width="100%" height="80" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
  introduction:
    # I am Wenjie(Clark) Hu, currently studying data science at the Univeristy of Wroclaw in Poland. 
    # I am very interested in autonomous driving and AI fields. My experience primarily revolves around Python and its ecosystem of toolkits. 
    # Beyond my tech interests, I find joy in activities like table tennis, hiking, and engaging in cultural exchanges. 
    # I speak Mandarin ChineseğŸ‡¨ğŸ‡³ & English ğŸ‡¬ğŸ‡§ and am currently learning French ğŸ‡«ğŸ‡·. 
    # If you listen to <font color='orange'>Taylor Swift</font>, we are good friends. 
    # <p align="center"><br /></p><p align="center"> <img src="https://s2.loli.net/2022/08/05/vdC7NzFZYmgtkJn.jpg" style="width:45%; margin-right:2%;"/>
    # <img src="https://s2.loli.net/2023/09/22/PUXIHfVABeq7nKy.jpg" style="width:45%;" /></p>
  blog: 
    # <ul class="trm-list">
    #   <li>BSc Computer Science - Maynooth University, Ireland </li>
    #   <li>MSc Data Science - University of WrocÅ‚aw, Poland </li>
    # </ul>
  privacy: 
    # Production Engineer at <u>WeRide</u>, Guangzhou, China [Mar 2021 - Aug 2021] At [WeRide](https://www.weride.ai/en/), I worked as a test-developer responsible for data analysis and high-definition map-related work. There, I touched the top-level of self-driving technology in the world.<br /> 
    # <p align="center"><img src="https://s2.loli.net/2022/08/05/PQcuM6ZqbxJC8wG.jpg" style="width:30%; margin-right:2%;"/> <img src="https://s2.loli.net/2022/08/05/PESytRIedc6qNBw.jpg" alt="Image 2" style="width:30%;" />
    # <img src="https://s2.loli.net/2022/08/05/bM3qVNftOlKrYk2.jpg" alt="Image 3" style="width:30%;" />
    # </p>
    # Test Engineer at <u>MoonX</u>, Shenzhen, China [Dec 2018 - Mar 2021]
    # During my time at [MoonX](https://www.weride.ai/en/muyue-en/), I was responsible for autonomous vehicle road testing and data analysis. I also worked closely with businesses and delivered self-driving vehicles to clients. I got my hands dirty in Cyber-RT, Linux, Python, and Docker and have comprehensive knowledge of autonomous driving systems.
    # <br>
    # <p align="center">
    # <img src="https://s2.loli.net/2022/08/05/nlgXcvJ98KoSwrW.jpg" alt="Image 1" style="width:45%; style="width:45%; margin-right:2%;"/>
    # <img src="https://s2.loli.net/2022/08/05/hV2dcMH9g5GZIlK.jpg" alt="Image 2" style="width:45%;" /></p>

  

# Footer settings
footer:
  # Hexo link (Powered by Hexo).
  powered:
    enable: false
  # Beian icp information for Chinese users. In China, every legal website should have a beian icp in website footer.
  # https://beian.miit.gov.cn/
  beian:
    enable: false
    icp: 
  # Copyright date
  copyright_year: 2024
  # 
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 07/01/2024 00:00:00
  #
  custom_text: #Hosted by <a href="https://github.com" rel="noopener" target="_blank">Github Pages</a>

# Here is a collection of articles related to configuration.
#### Article configuration start ###
# Reward (Donate)
# If enable true, reward would be displayed in every posts and pages by default.
# You can show or hide reward in a specific page throuth `reward: true | false` in Front Matter.
reward:
  enable: false
  comment: reward.comment
  # url:
  methods:

# Article table of contents
toc:
  enable: true
  list_number: true
  post_title: true
  max_depth: 3
  min_depth: 1

# Archive page
archive:
  type: more # less more

# Creative Commons 4.0 International License.
# https://creativecommons.org/licenses/
# Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
# You can set a language value if you prefer a translated version of CC license.
# CC licenses are available in 39 languages, where you can find the specific and correct abbreviation you need.
# Valid values of language: deed.zh, deed.en, deed.ja, etc.
creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: false
  clipboard: false
# Customize the cover image
cover:
  default: img/block.jpg
  type: img # img || date || random

# The previous and the next article
post_pagination: 
  enable: true 
  type: small # large || small

# img loading="lazy"
lazyload:
  enable: true

# Displays outdated notice for a post (æ–‡ç« è¿‡æœŸæé†’)
notice_outdate:
  enable: false
  style: flat # style: simple/flat
  limit_day: 365 # When will it be shown
  position: top # position: top/bottom
#### Article configuration end ###

# Page Visit Statistics
web_analytics:  
  enable: false 
  baidu:   # Baidu key
  google:  # Tracking ID for Google statistics
  tencent: # Tencent statistics
    sid:
    cid:

# comment
comment:
  bComments:
    enable: false
    env: # è…¾è®¯äº‘ç¯å¢ƒid
  twikoo:
    enable: false
    envId:   # è…¾è®¯äº‘ç¯å¢ƒid
  # region: # ç¯å¢ƒåœ°åŸŸï¼Œé»˜è®¤ä¸º ap-shanghaiï¼Œå¦‚æœæ‚¨çš„ç¯å¢ƒåœ°åŸŸä¸æ˜¯ä¸Šæµ·ï¼Œéœ€ä¼ æ­¤å‚æ•°
  # option: # ç”¨äºåŒºåˆ†ä¸åŒæ–‡ç« çš„è‡ªå®šä¹‰ js è·¯å¾„ï¼Œå¦‚æœæ‚¨çš„æ–‡ç« è·¯å¾„ä¸æ˜¯ location.pathnameï¼Œéœ€ä¼ æ­¤å‚æ•°
  giscus:
    enable: true
    repo:  wenjie-hoo/magic-kangaroo
    repo-id: R_kgDOMQKn2w
    category: General
    category-id: DIC_kwDOMQKn284Cgk3f
    mapping: pathname
    reactions-enabled: 1
    emit-metadata: 0
    lang: en
    theme: 
      light: light
      dark: transparent_dark

# Theme mode 
theme: 
  switch: true 
  default: style-light # style-light style-dark

# Service Worker
sw: false

# Post wordcount
# https://github.com/willin/hexo-wordcount
wordcount:
  enable: true
  count: true
  time: true

# That is it only render those page which has `katex: true` in Front-matter.
# math fomula
# https://katex.org/
katex:
  copy_tex: true
  global: true
  # Options are for katex rendering options: https://katex.org/docs/options.html
  # In page katex options are also possible and will be merged
  options: {}

# Blog search
search:
  enable: true
  type: local #local /engine
  href: 'https://www.google.com/search?q=site:'
  # href: "https://www.baidu.com/s?wd=site:"
  # href: "https://www.bing.com/search?q=site:"
  domain: 

# Think of swup as being pjax on steroids. The concepts are similar to those used in barba.js or other transition libraries.
# https://swup.js.org/
# Whether swup is enabled
swup: false

# Datetime formatting
datetime_foramt:
  post_card:
    type: date # date || updated
    date: YYYY/MM/DD
    time: HH:mm
    cover_date: DD
    cover_date2: YYYY/MM
  post_info:
    type: date
    date: YYYY/MM/DD
    time: HH:mm
  archive:
    type: date
    date: YYYY/MM/DD
    time: HH:mm

# Home page category card configuration
categorie_card:
  enable: true
  len: 6
  list: ['travel','thought']

# Lower right button
rightside:
  readmode: true
  aside: true

# Replace Broken Images 
error_img:
  flink: /img/friend_404.gif
  post_page: /img/404.jpg

# Code highlighting configuration
highlight:
  theme: true # 
  title: default # mac | default
  copy: true # copy button
  lang: true # show the code language
  code_word_wrap: fasle #
  height_limit: false # unit: px

# Customize the template path
layout:
  path: layout
  # layout
  main:  _partial/main
  header: _partial/header
  banner: _partial/banner
  sidebar: _partial/sidebar/index
  footer: _partial/footer
  # post
  post_info: _partial/post/post-info
  post_content: _partial/post/post-content
  reward: _partial/post/reward
  post_copyright: _partial/post/post-copyright
  post_next_prev: _partial/post/post-next-prev
  post_card: _partial/post/post-card
  post_card_mini: _partial/post/post-card-mini
  # widget
  header_logo: _widget/header-logo
  header_menu: _widget/header-menu
  header_theme: _widget/header-theme
  header_search: _widget/header-search
  categorie: _widget/categorie
  paginator: _widget/paginator
  fixed_btn: _widget/fixed-btn
  post_toc: _widget/post-toc
	about_card: _widget/about-card
	search: _widget/search
  sidebar_user: _partial/sidebar/card/user
  sidebar_social: _partial/sidebar/card/social
  sidebar_info: _partial/sidebar/card/info
  sidebar_email: _partial/sidebar/card/email
  # third-party
  comment: _third-party/comment/index
  analytics: _third-party/web-analytics
  # animation
  page_loading: _partial/preloader/page-preloader
  mode_change:  _partial/preloader/change-mode-preloader
  # page
  page_about: _partial/page/about
  page_archive: _partial/page/archive
  page_category: _partial/page/category
  page_index: _partial/page/index
  page_links: _partial/page/links
  page_post: _partial/page/post
  page_tag: _partial/page/tag
	# other
	script: _partial/script
	head: _partial/head

not_found: 
	path: /
	name: not_found.name
	text: not_found.text